Add GraphQLQuery #14
aicers/github-dashboard-client pull request #15
Opened 2022-07-28 23:35 UTC by BLYKIM

- Changes
modified:   Cargo.lock
modified:   Cargo.toml
new file:   src/graphql.rs
modified:   src/home.rs
new file:   src/schema.graphql
new file:   src/server_issues.graphql

Close #14

2022-07-28 23:47 UTC, msk commented
커밋 로그에 어떤 파일을 변경했는지는 안 적어도 됩니다. 어차피 git log로 쉽게 알 수 있는 내용이라서요. 그보다는 [코드 레벨에서의 변경 이유](https://cbea.ms/git-commit/#why-not-how)를 적어주세요. 이 PR에서 고칠 필요는 없고, 다음부터 유념해주세요.

2022-07-28 23:48 UTC, BLYKIM commented
네 감사합니다

2022-07-28 23:51 UTC, msk requested changes
graphql.rs는 안 쓰이는 것 같은데, 불필요한 파일은 삭제해주세요.

2022-07-28 23:52 UTC, BLYKIM commented
아 맞습니다 수정할게요

2022-07-29 00:22 UTC, msk approved these changes

2022-07-29 00:22 UTC, merged