Set issues link
aicers/github-dashboard-client pull request #22
Opened 2022-08-04 03:13 UTC by kimhanbeom

Resolves: #21

2022-08-04 06:22 UTC, msk requested changes

2022-08-04 06:22 UTC, msk commented on src/home.rs
> +                            let href =format!("https://github.com/{}/{}/issues/{}",owner,repo,number);
`=` 다음, `,` 다음에 공백을 넣어주세요. 매크로 내부이다보니 rustfmt이 고치질 못하나봅니다.

2022-08-04 06:22 UTC, msk commented on src/server_issues.graphql
> +                repo,
일관성을 위해 `,`는 전부 안 쓰는 것으로 합시다.

2022-08-04 07:56 UTC, kimhanbeom commented
해당 사항 수정 완료 했습니다.

2022-08-04 20:51 UTC, msk requested changes

2022-08-04 20:51 UTC, msk commented on src/server_issues.graphql
> +        edges{
포맷의 일관성을 위해 `{` 앞에는 공백을 넣어주세요.

2022-08-04 23:31 UTC, kimhanbeom commented
쿼리 포멧 수정 완료했습니다.

2022-08-05 01:14 UTC, msk approved these changes

2022-08-05 01:15 UTC, merged