Create web executable
aicers/github-dashboard-client pull request #3
Opened 2022-07-16 01:23 UTC by marioEinsis

- Added main.rs as well as home.rs
- Created cargo.toml
- trunk serve creates prints out AICE Github Dashboard

2022-07-16 01:57 UTC, msk requested changes

2022-07-16 01:57 UTC, msk commented on Cargo.toml
> +yew = "^0.19"
Please end a text file with a newline. See [Why should text files end with a newline?](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline) for justification.

2022-07-16 01:57 UTC, msk commented on README.md
> +
This empty line is redundant.

2022-07-16 01:57 UTC, msk commented on src/main.rs
> +    yew::start_app_with_props::<crate::home::Model>(props);
It is inconsistent to use `crate::home::Props` as `Props` but `crate::home::Model` as `crate::home::Model`. Use both in their short forms (`Props` and `Model`) or use both in their complete forms (`crate::home::Props` and `crate::home::Model`), but do not mix two different forms in a single module.

2022-07-16 16:40 UTC, marioEinsis commented on src/main.rs
> +    yew::start_app_with_props::<crate::home::Model>(props);
Got it!!

2022-07-16 16:43 UTC, marioEinsis commented on src/main.rs
> +    yew::start_app_with_props::<crate::home::Model>(props);
Which form is more preferred? The short form or the complete form?

2022-07-16 20:02 UTC, msk commented on src/main.rs
> +    yew::start_app_with_props::<crate::home::Model>(props);
I would keep them short as long as it is clear what they are referring to from the context.

2022-07-17 10:57 UTC, msk commented on Cargo.toml
> +yew = "^0.19"
index.html has the same problem.

2022-07-17 11:19 UTC, msk requested changes

2022-07-17 11:19 UTC, msk commented on src/main.rs
> +    println!("AICE Github Dashboard");
Remove this line since an end user won't see this message anyway.

2022-07-17 11:19 UTC, msk commented on index.html
> +    <title>AICE Github Dashboard</title>
`Github` -> `GitHub`

2022-07-17 11:19 UTC, msk commented on src/home.rs
> +#[derive(Properties, Clone, PartialEq)]
Add a blank line between `struct` definitions for readability.

2022-07-17 18:46 UTC, msk commented on index.html
> +    <title>AICE Github Dashboard</title>
This hasn't been resolved.

2022-07-17 18:50 UTC, marioEinsis commented on index.html
> +    <title>AICE Github Dashboard</title>
Thank you for catching that. I capitalized the one in home.rs.

2022-07-17 21:44 UTC, msk approved these changes

2022-07-17 21:44 UTC, merged